# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 650fca5c1c65e9bb345c8b05ac1b6b52fc99848ffe83e443d6f7cd67ef4d3b75b9a8755e11ad94c2879c2a7ee70d4606c95e55f5fe93fa81988dd8c93d2d7309

test:
  secret_key_base: d321468f893170d33fd26f6e7f5282f9acbc9ca8ef55351254818311beee1c11055f113e2aa115ac8cfdb10d4d3c0c1cb3d46ffb6461b5f257b02437a9a34690

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
